const main = async () => {
  console.log('main');
};

main().catch(e => console.error(e));
